-- 001_create_users.sql
-- Tabla de usuarios. Entidad base del sistema.

CREATE TABLE IF NOT EXISTS users (
  id          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  last_name   VARCHAR(100) NOT NULL,
  email       VARCHAR(255) NOT NULL,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

  -- Validacion de formato a nivel de BD, complementaria a la del servicio.
  CONSTRAINT users_email_format_chk CHECK (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  CONSTRAINT users_name_not_blank_chk CHECK (length(btrim(name)) > 0),
  CONSTRAINT users_last_name_not_blank_chk CHECK (length(btrim(last_name)) > 0)
);

-- Unicidad de email insensible a mayusculas: "Mario@x.com" y "mario@x.com"
-- son el mismo usuario. Un UNIQUE plano sobre la columna no lo impediria.
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_uidx ON users (lower(email));

COMMENT ON TABLE users IS 'Usuarios que pueden tener tareas asignadas';
COMMENT ON INDEX users_email_lower_uidx IS 'Email unico, comparado en minusculas';
