-- 002_create_tasks.sql
-- Tabla de tareas y el enum de estado.

-- El estado es un ENUM y no un VARCHAR libre: la integridad queda garantizada
-- por la base de datos y no depende de que la capa de aplicacion se comporte.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_status') THEN
    CREATE TYPE task_status AS ENUM ('open', 'archived');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS tasks (
  id           INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        VARCHAR(200) NOT NULL,
  description  TEXT,
  status       task_status  NOT NULL DEFAULT 'open',
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  archived_at  TIMESTAMPTZ,

  CONSTRAINT tasks_title_not_blank_chk CHECK (length(btrim(title)) > 0),

  -- status y archived_at no pueden contradecirse. Esta restriccion es la que
  -- hace verificable el requisito de "archivar exactamente una vez": una tarea
  -- archivada siempre tiene fecha, y una abierta nunca la tiene.
  CONSTRAINT tasks_archived_consistency_chk CHECK (
    (status = 'archived' AND archived_at IS NOT NULL) OR
    (status = 'open'     AND archived_at IS NULL)
  )
);

-- Soporta GET /tasks?status=open|archived
CREATE INDEX IF NOT EXISTS tasks_status_idx ON tasks (status);

COMMENT ON TABLE tasks IS 'Tareas asignables a uno o varios usuarios';
COMMENT ON COLUMN tasks.archived_at IS 'Se puebla al archivar; NULL mientras la tarea sigue abierta';
