-- 003_create_task_assignments.sql
-- Relacion muchos-a-muchos entre tareas y usuarios.
-- Es la tabla central del reto: aqui vive el "completado" por persona.

CREATE TABLE IF NOT EXISTS task_assignments (
  id            INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id       INTEGER     NOT NULL,
  user_id       INTEGER     NOT NULL,
  completed     BOOLEAN     NOT NULL DEFAULT false,
  completed_at  TIMESTAMPTZ,
  assigned_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT task_assignments_task_fk
    FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,

  -- RESTRICT y no CASCADE: borrar un usuario con tareas asignadas alteraria
  -- silenciosamente el conteo de completados y podria archivar una tarea sola.
  CONSTRAINT task_assignments_user_fk
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,

  CONSTRAINT task_assignments_completed_consistency_chk CHECK (
    (completed = true  AND completed_at IS NOT NULL) OR
    (completed = false AND completed_at IS NULL)
  )
);

-- Requisito explicito del reto: reasignar un usuario ya asignado no debe
-- duplicar la relacion. La garantia vive en la BD, no en un SELECT previo,
-- para que siga siendo cierta con requests concurrentes.
CREATE UNIQUE INDEX IF NOT EXISTS task_assignments_task_user_uidx
  ON task_assignments (task_id, user_id);

-- Compuesto y no solo (user_id): GET /users filtra las tareas *pendientes*
-- de cada usuario, y asi el filtro por completed se resuelve dentro del
-- indice. Por columna lider sigue sirviendo a GET /users/:idUser/tasks.
CREATE INDEX IF NOT EXISTS task_assignments_user_completed_idx
  ON task_assignments (user_id, completed);

COMMENT ON TABLE task_assignments IS 'Asignacion de un usuario a una tarea y su estado de completado';
COMMENT ON INDEX task_assignments_task_user_uidx IS 'Impide duplicar la relacion tarea-usuario';
