-- 004_create_notification_attempts.sql
-- Bitacora de intentos de notificacion al sistema externo (NOTIFY_URL).
-- Cada intento es una fila; se consulta en GET /tasks/:idTask/notifications.

CREATE TABLE IF NOT EXISTS notification_attempts (
  id              INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id         INTEGER     NOT NULL,
  attempt_number  INTEGER     NOT NULL,
  http_status     INTEGER,
  success         BOOLEAN     NOT NULL DEFAULT false,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT notification_attempts_task_fk
    FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,

  CONSTRAINT notification_attempts_number_chk CHECK (attempt_number >= 1),

  -- NULL cuando el destino no respondio (timeout o error de red).
  CONSTRAINT notification_attempts_http_status_chk
    CHECK (http_status IS NULL OR http_status BETWEEN 100 AND 599)
);

-- Dos garantias en un solo indice: no puede registrarse dos veces el mismo
-- numero de intento para una tarea, y ordena la lectura del endpoint.
CREATE UNIQUE INDEX IF NOT EXISTS notification_attempts_task_number_uidx
  ON notification_attempts (task_id, attempt_number);

COMMENT ON TABLE notification_attempts IS 'Un registro por cada intento de POST a NOTIFY_URL';
COMMENT ON COLUMN notification_attempts.http_status IS 'NULL si el destino no respondio';
