-- 005_create_idempotency_keys.sql
-- Soporte del header Idempotency-Key en los endpoints POST.

CREATE TABLE IF NOT EXISTS idempotency_keys (
  id               INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idem_key         VARCHAR(255) NOT NULL,
  endpoint         VARCHAR(255) NOT NULL,
  request_hash     VARCHAR(64)  NOT NULL,
  response_status  INTEGER,
  response_body    JSONB,
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT idempotency_keys_key_not_blank_chk CHECK (length(btrim(idem_key)) > 0),
  CONSTRAINT idempotency_keys_response_status_chk
    CHECK (response_status IS NULL OR response_status BETWEEN 100 AND 599)
);

-- La pieza que hace funcionar la idempotencia bajo concurrencia: el segundo
-- request en paralelo choca contra este indice al insertar, en vez de ganar
-- una carrera de lectura. La misma llave puede reusarse en otro endpoint.
CREATE UNIQUE INDEX IF NOT EXISTS idempotency_keys_key_endpoint_uidx
  ON idempotency_keys (idem_key, endpoint);

-- Para purgar llaves viejas periodicamente.
CREATE INDEX IF NOT EXISTS idempotency_keys_created_at_idx ON idempotency_keys (created_at);

COMMENT ON TABLE idempotency_keys IS 'Respuestas ya calculadas por Idempotency-Key y endpoint';
COMMENT ON COLUMN idempotency_keys.request_hash IS 'SHA-256 del body, detecta misma llave con distinto cuerpo';
COMMENT ON COLUMN idempotency_keys.response_status IS 'NULL mientras la operacion sigue en vuelo';
